[package]
name = "gofi"
version = "0.1.0"
edition = "2024"

[dependencies]
rdev = "0.5"
walkdir = "2.5"
fuzzy-matcher = "0.3.7"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
eframe = "0.26"
